id: P1B57DDEB
initial_creation_type: ocr
source_metadata:
  volumes:
    a6bc4379a6734bd2b4e586ac646088e4:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་ཆོག།
      total_pages: 1044
      volume_number: 38
